services:
  - type: web
    name: ai-helper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: "ضع_المفتاح_هنا"
